stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar

deploy:
  stage: deploy
  script:
    - chmod +x ./deploy.sh
    - ./deploy.sh
  only:
    - main