stages:
  - build
  - test
  - deploy

variables:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "wifros/my_docker"
  DOCKER_TAG: "$CI_COMMIT_SHA"
  DOCKER_LATEST_TAG: "latest"

before_script:
  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"

build:
  stage: build
  script:
    - cd spring
    - mvn clean package

build_image:
  stage: build
  script:
    - docker build --platform linux/amd64 -f spring/Dockerfile -t $DOCKER_IMAGE:$DOCKER_TAG spring/
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:$DOCKER_LATEST_TAG
    - docker push $DOCKER_IMAGE:$DOCKER_LATEST_TAG

test:
  stage: test
  script:
    - docker run --rm $DOCKER_IMAGE:$DOCKER_LATEST_TAG ./run-tests.sh

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_IMAGE:$DOCKER_LATEST_TAG
    - docker stop my_app_container || true
    - docker rm my_app_container || true
    - docker run -d --name my_app_container -p 8081:8080 $DOCKER_IMAGE:$DOCKER_LATEST_TAG
