image: eclipse-temurin:17

services:
  - docker:dind
  - mariadb:latest

stages:
  - build
  - run

build:
  stage: build
  script:
    - cd spring
    - chmod +x mvnw
    - export MAVEN_OPTS="-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    - ./mvnw clean package
  artifacts:
    paths:
      - spring/target/*.jar
    expire_in: 1 week
  only:
    changes:
      - spring/**/*

run:
  stage: run
  script:
    - cd spring/target
    - echo "Starting new instance..."
    - java -jar *.jar
  only:
    changes:
      - spring/**/*