stages:
  - build
  - deploy
variables:
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-17.0.10.0.7-2.el9.x86_64"
build:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-17.0.10.0.7-2.el9.x86_64
    - export PATH=$JAVA_HOME/bin:$PATH
    - echo "JAVA_HOME is set to $JAVA_HOME"
    - echo "PATH is set to $PATH"
    - cd spring
    - mvn clean package
    - docker build -t my-springboot-app .
  only:
    changes:
      - spring/**/*

deploy:
  stage: deploy
  script:
    - docker stop my-springboot-app || true
    - docker rm my-springboot-app || true
    - docker run -d --name my-springboot-app -p 80:80 my-springboot-app
  only:
    changes:
      - spring/**/*