image: docker:latest

services:
  - docker:dind
  - mariadb:latest

variables:
  MYSQL_DATABASE: ssafyweb
  MYSQL_USER: scott
  MYSQL_PASSWORD: tiger
  MYSQL_ROOT_PASSWORD: ssafy

stages:
  - test
  - build
  - run

test_mariadb_connection:
  stage: test
  image: mariadb
  script:
    #- apt-get update && apt-get install -y default-mysql-client
    - mysql --host=WiFros.iptime.org --port=3306 --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE -e "SELECT 1"
  only:
    changes:
      - spring/**/*

build:
  stage: build
  script:
    - cd spring
    - chmod +x mvnw
    - export MAVEN_OPTS="-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    - ./mvnw clean package
  artifacts:
    paths:
      - spring/target/*.jar
    expire_in: 1 week
  only:
    changes:
      - spring/**/*

run:
  stage: run
  script:
    - cd spring/target
    - java -jar *.jar --spring.datasource.url=jdbc:mariadb://mariadb:3306/$MYSQL_DATABASE --spring.datasource.username=$MYSQL_USER --spring.datasource.password=$MYSQL_PASSWORD
  only:
    changes:
      - spring/**/*