variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/.m2

default:
  image: maven:3.9.6-jdk-17

stages:
  - build
  - test

Build:
  stage: build
  script:
    - mvn install -DskipTests

Test:
  stage: test
  script:
    - mvn test
