image: eclipse-temurin:17

stages:
  - build

build:
  stage: build
  script:
    - cd spring
    - export MAVEN_OPTS="-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    - ./mvnw clean package
  artifacts:
    paths:
      - spring/target/*.jar
    expire_in: 1 week
  only:
    changes:
      - spring/**/*