stages:
  - build
  - deploy

build-spring:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - cd spring
    - mvn clean package
  artifacts:
    paths:
      - spring/target/*.jar
  only:
    changes:
      - spring/**/*

deploy-spring:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd spring
    - docker build -t your-docker-hub-username/your-spring-image .
    - docker login -u your-docker-hub-username -p your-docker-hub-password
    - docker push your-docker-hub-username/your-spring-image
  only:
    changes:
      - spring/**/*