stages:
  - build
  - deploy

build:
  stage: build
  image: maven:4.0.0-openjdk-17
  script:
    - cd spring
    - mvn clean package
    - docker build -t my-springboot-app .
  only:
    changes:
      - spring/**/*

deploy:
  stage: deploy
  script:
    - docker stop my-springboot-app || true
    - docker rm my-springboot-app || true
    - docker run -d --name my-springboot-app -p 80:80 my-springboot-app
  only:
    changes:
      - spring/**/*