image: maven:latest

stages:          
  - build
  - test
  - package
  - deploy

build-job:       
  stage: build
  script:
    - "cd cicd/cicd"
    - echo "Compiling the code..."
    - "mvn compile"
    - echo "Compile complete."

test-job:   
  stage: test
  script:
    - "cd cicd/cicd"
    - echo "Running unit tests.."
    - "mvn test"

package-job:   
  stage: test   
  script:
    - "cd cicd/cicd"
    - echo "Package the code"
    - "mvn package"

deploy-job:      
  stage: deploy  
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."